### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Madis0** [adam-p/breached#3]
Is there a good reason why it has been marked as incompatible for Firefox for Android?

**Comment by adam-p** [comment]
The first release was marked as compatible with Android, but I couldn't actually make it work. So I removed Android. 

I ought to do some testing in an emulator, but... I'll make a new release right now enabling Android. We can find out the hard way. (I don't see a way to enable without another release.)

I'm going to close this. Optimistically.

**Comment by Madis0** [comment]
The notification, button and button "popup" (actually a full page on mobile)  work for me. If you'd like to improve it, you could make it so the popup text is responsive, aka wouldn't require zooming in. Other than that it works great!

**Comment by adam-p** [comment]
I think the breach display on Android is improved now. It's not great, though. I have to specify a minimum width or else the popup doesn't look right on desktop browsers, but that introduces a potential problem for narrow mobile browsers. 

Anyway, it looks okay on my phone now. Let me know how it is for you. If the current styling isn't good enough, then I can surely make it behave differently if mobile Firefox is detected.

**Comment by Madis0** [comment]
Yup, it looks good to me too.
