### ISSUE TITLE
Breached-like extension inside Firefox

### ISSUE THREAD

**Issue by Madis0** [adam-p/breached#5]
Just wanted to let you know of this:

> We’ve started working on integrating haveibeenpwned.com warnings into Firefox, [you can follow development here](https://github.com/nhnt11/BreachAlerts).

_from [These Weeks in Firefox: Issue 28](https://blog.nightly.mozilla.org/2017/11/22/these-weeks-in-firefox-issue-28/)_

Perhaps you could even help them out?

**Comment by claustromaniac** [comment]
I was going to inform @adam-p of this but you beat me to it. 

I wouldn't be surprised if Mozilla ended up having different priorities, or messing up somehow, and then this extension wouldn't necessarily become redundant.

**Comment by adam-p** [comment]
Huh. Thanks for letting me know. I'll reach out to them, but there's really not much to Breached, so I doubt how useful it'll be to them.

(I probably don't have time to help them much. Full time job plus family plus other hobby code equals... very little extra time.)
